bluzelle/swarmDB

README.md
qa/integration-tests.sh

Some content changed and I restructured so that it's hopefully easier to follow.

Update README and add qa script

---

crud/test/crud_tests.cpp
node/node.cpp

* responses should be sent with binary opcode

KEP-307 Update CRUD to use protobuf messages

---

scripts/crud

* fixed wrong handler being called for "has" command

KEP-396 Create Python script to issue CRUD commands using protobuf

---

crud/CMakeLists.txt
crud/crud.cpp
crud/crud.hpp
crud/subscription_manager.cpp
crud/subscription_manager.hpp
crud/subscription_manager_base.hpp
crud/test/CMakeLists.txt
crud/test/crud_tests.cpp
crud/test/subscription_manager_test.cpp
include/bluzelle.hpp
mocks/mock_subscription_manager_base.hpp
node/session.cpp
node/session.hpp
node/session_base.hpp
node/test/session_test.cpp
proto/database.proto
raft/raft.cpp
scripts/crud
swarm/main.cpp

* disabled idle timeout
* RAFT heartbeat now 4X faster
* reduced useless logging
* crud test script supports subscribe

KEP-289 Remove need to poll for update on keys

---

utils/http_get.cpp

KEP-499 Daemon intermittently unable to connect to peers on startup

---

swarm/main.cpp

KEP-540: Fixed the spelling mistake

---

.travis.yml
CMakeLists.txt

Just added the find package line that includes the OpenSSL package.

KEP-548: Add OpenSSL library to project

---

.gitignore
options/CMakeLists.txt
options/options.cpp
options/simple_options.cpp
options/simple_options.hpp
options/test/CMakeLists.txt
options/test/options_test.cpp
scripts/generate-key
utils/crypto.cpp
utils/crypto.hpp

Dameon uses own public key as uuid, script to generate such key

KEP-599: Daemon cryptographic identity

---

README.md

Description of auto add peers, and added comments and definitions for the signed key.

KEP-688 Updating readme to discuss auto add peer to swarm

---

pbft/pbft.cpp
pbft/pbft.hpp
pbft/pbft_config_store.cpp
pbft/pbft_config_store.hpp
pbft/pbft_configuration.cpp
pbft/pbft_configuration.hpp
pbft/test/CMakeLists.txt
pbft/test/pbft_config_store_test.cpp
pbft/test/pbft_configuration_test.cpp
pbft/test/pbft_join_leave_test.cpp
pbft/test/pbft_test_common.cpp
proto/bluzelle.proto
proto/pbft.proto

See https://bluzelle.atlassian.net/browse/KEP-573
Isabel has already seen this, apart from a few cosmetic changes.

KEP-573: dynamic peering

---

include/bluzelle.hpp
mocks/mock_pbft_service_base.hpp
pbft/database_pbft_service.cpp
pbft/database_pbft_service.hpp
pbft/dummy_pbft_service.cpp
pbft/dummy_pbft_service.hpp
pbft/pbft.cpp
pbft/pbft_service_base.hpp
pbft/test/database_pbft_service_test.cpp

Initial implementation of state interface for pbft_service.  I'm putting this in as a pull request since we're rushing to complete this functionality. Please comment.

KEP-781: pbft service supports get and set state at checkpoint

---

crud/crud.cpp
crud/crud.hpp
crud/crud_base.hpp
crud/test/crud_test.cpp
mocks/mock_storage_base.hpp
proto/database.proto
storage/mem_storage.cpp
storage/mem_storage.hpp
storage/rocksdb_storage.cpp
storage/rocksdb_storage.hpp
storage/storage_base.hpp
storage/test/storage_test.cpp

* includes the removal of auto creating of a database (KEP-813)

KEP-580 Add create_db, delete_db & has_db etc. to crud metadata

---

include/bluzelle.hpp
mocks/mock_pbft_service_base.hpp
pbft/pbft.cpp
pbft/pbft.hpp
pbft/pbft_operation.cpp
pbft/pbft_operation.hpp
pbft/test/pbft_test.cpp
pbft/test/pbft_test_common.cpp
pbft/test/pbft_test_common.hpp
utils/CMakeLists.txt
utils/bytes_to_debug_string.cpp
utils/bytes_to_debug_string.hpp

open and sends a response when the operation is eventually executed.

KEP-801: When forwarding a request to primary, replica holds session

---

crud/crud.cpp
crud/crud.hpp
crud/crud_base.hpp
mocks/mock_crud_base.hpp
mocks/mock_pbft_service_base.hpp
mocks/mock_storage_base.hpp
pbft/database_pbft_service.cpp
pbft/database_pbft_service.hpp
pbft/dummy_pbft_service.cpp
pbft/dummy_pbft_service.hpp
pbft/pbft.cpp
pbft/pbft.hpp
pbft/pbft_service_base.hpp
pbft/test/database_pbft_service_test.cpp
pbft/test/pbft_catchup_test.cpp
storage/mem_storage.cpp
storage/mem_storage.hpp
storage/rocksdb_storage.cpp
storage/rocksdb_storage.hpp
storage/storage_base.hpp
storage/test/storage_test.cpp

Interface changes, code and tests to support saving, getting and setting of service state, in particular for mem_storage.

KEP-815: crud and storage support for snapshots

---

pbft/database_pbft_service.cpp
pbft/database_pbft_service.hpp
pbft/pbft.cpp
pbft/test/database_pbft_service_test.cpp

KEP-838: pbft_database_service passes the pbft_operation ptr back to

---

pbft/pbft.cpp

KEP-897: bugfix for db state sync

---

audit/audit.cpp
pbft/pbft.cpp
pbft/pbft.hpp
pbft/test/pbft_catchup_test.cpp
pbft/test/pbft_join_leave_test.cpp
pbft/test/pbft_proto_test.cpp
pbft/test/pbft_proto_test.hpp
proto/pbft.proto

KEP-904: Caught up node doesn't switch to current view number

---

swarm/main.cpp

State directory will remain for pbft & user databases

KEP-490 Remove .state Functionality

---

pbft/test/pbft_newview_test.cpp

Unit test for KEP-903

---

mocks/mock_storage_base.hpp
pbft/operations/pbft_operation_manager.cpp
pbft/operations/pbft_persistent_operation.cpp
pbft/operations/pbft_persistent_operation.hpp
pbft/operations/test/pbft_persistent_operation_test.cpp
pbft/test/pbft_test_common.hpp
storage/mem_storage.cpp
storage/mem_storage.hpp
storage/rocksdb_storage.cpp
storage/rocksdb_storage.hpp
storage/storage_base.hpp
storage/test/storage_test.cpp

Added various range queries to storage to provide support for finding/removing pbft operation state.

KEP-1012 pbft_operation_manager existential queries

---

pbft/test/pbft_test_common.hpp
swarm/main.cpp

KEP-974 Persistence turned on by default

---

pbft/pbft.cpp

KEP-1169: Notify failure detector when forwarded join request is

---

pbft/database_pbft_service.cpp

Fix for situation where we adopt checkpoint state while processing backlogged operations.

KEP-1236: fix for race condition processing operations

---

monitor/monitor.cpp
monitor/monitor.hpp
monitor/test/monitor_test.cpp
options/simple_options.cpp
options/simple_options.hpp

KEP-1222: Collate monitor output, to reduce log spam and network

---

pbft/pbft_persistent_state.hpp

debug output for diagnosing failure to write persistent value to storage.

Added debug info to failures when storing persistent state

---

crud/crud.cpp
crud/test/crud_test.cpp
include/bluzelle.hpp
mocks/mock_options_base.hpp
options/options.cpp
options/options.hpp
options/options_base.hpp
options/simple_options.cpp
options/simple_options.hpp
options/test/options_test.cpp
proto/database.proto
proto/status.proto
status/status.cpp
status/status.hpp
status/test/status_test.cpp
swarm/main.cpp

* swarm id added to status response
* size request includes max_size if one is set

KEP-1151 Add new attributes to the status/size messages

---

README.md
cmake/boost.cmake
monitor/CMakeLists.txt

KEP-1362 Updated darwin to 1.70

---

pbft/pbft_persistent_state.hpp
utils/http_req.cpp

debugging info to track down which variable is the problem.
Also added certificate directory for Ubuntu

KEP-1500 - added info to exception, also added cert directory for Ubuntu

---

README.md
pkg/debian/CMakeLists.txt
utils/crypto.cpp

KEP-1443 Replace use of libCurl with Boost Beast

KEP-1557 Prune curl references from docs

---

pbft/pbft.cpp

Most of the fix for this is in KEP-1428. This is just some extra safety around the config pointer.

KEP-1539 - additional safety checks

---

pbft/pbft.cpp
pbft/pbft.hpp

Fix for testnet-2 crash July 18 2019

KEP-1618 - don't add requests to newview if we don't have them

---

pbft/database_pbft_service.cpp
pbft/pbft.cpp
pbft/pbft.hpp
pbft/pbft_failure_detector.cpp

off-by-one in state application, debug messages

KEP-1675: don't send empty newview message with state, fix for
