- raft/CMakeLists.txt
- raft/log_entry.hpp
- raft/raft.cpp
- raft/raft.hpp
- raft/test/CMakeLists.txt
- raft/test/raft_test.cpp
- swarm/main.cpp
Implements RAFT log state and log persistence. As a daemon commits entries, each entry is appended to a log file on local storage, at the same time the RAFT state variables are also persisted to a separate log file.
If the daemon is stopped and later restarted, the log entries are used to rehydrate the daemon to the point at which it was shut down.
In addition, the daemon storage is reloaded from the loaded log entries.
> KEP-277: RAFT persistence implementation

- raft/raft.cpp
Replaced ascii art with easily matchable state strings:
"RAFT State: Follower"
"RAFT State: Candidate"
"RAFT State: Leader"
There are no unit tests for this change.
> KEP-321: Add easily matchable Daemon states logging

- crud/crud.cpp
- node/node.cpp
- node/test/node_test.cpp
- raft/raft.cpp
- raft/test/raft_test.cpp
- swarm/main.cpp
To find the offending log messages, that potentially show key/value contents I did a regex search with
'LOG\s*+('
which gave me the locations of all of the LOG instances and also
'cout'
which did have a few hits... I removed the one with a "msg" in it.
Instead of completely removing the large LOG messages, they were all of the
LOG(debug) << "Sending WS message:\n" << resp_msg->toStyledString();
variety, I append a substring
LOG(debug) << "Sending WS message:\n" << resp_msg->toStyledString().substr(0, 60) << "...";
and ellipses to indicate the truncation.
If this is not satisfactory, I can just remove them.
> KEP-349 - LOGs no longer show entire append entry messages

- bootstrap/bootstrap_peers.cpp
- crud/crud.cpp
- crud/test/crud_tests.cpp
- include/bluzelle.hpp
- mocks/mock_raft_base.hpp
- node/node.cpp
- node/test/node_test.cpp
- options/options.cpp
- options/options_base.hpp
- raft/CMakeLists.txt
- raft/log_entry.hpp
- raft/raft.cpp
- raft/raft.hpp
- raft/raft_base.hpp
- raft/raft_log.cpp
- raft/raft_log.hpp
- raft/test/CMakeLists.txt
- raft/test/raft_log_test.cpp
- raft/test/raft_test.cpp
- swarm/main.cpp
UPDATE
Isabel and I removed the logging functionality out of RAFT and into its own class to reduce confusion
regarding when something is logged as opposed to when it is committed (mainly my confusion).
I also fixed and intermittent bug w.r.t. writing the initial log entry to a file in the .state directory when the .state directory does not exist. 
END UPDATE
Here is the Dynamic Swarm Peer Membership functionality. Please have a quick look. Each sub task has been reviewed.
Note that this pull request also includes the change that increases the output of append entry log messages from 60 to 1024 characters.
> KEP-283 Dynamic Swarm Peer Membership

- options/options.cpp
- options/options.hpp
- options/options_base.hpp
- options/test/options_test.cpp
- swarm/main.cpp
The functionality to allow us to set the maximum storage setting in the config file, and display the maximum storage value and current storage size (the size in bytes of the .dat file).
> KEP-112 : KEP-450 and KEP-452 Setting and Display Storage Limits

- raft/raft.cpp
- raft/test/raft_test.cpp
The previous pull request was submitted with failing unit tests. After review, Isabel helped me undo the previous "fix" which caused the unit test failures and perform a fix that side steps the issue of attempting to access log entries that do not exist.
> KEP-469: Implemented fix for the 2 Node Swarm Remove Follower Crash

- raft/raft.cpp
- raft/raft.hpp
- raft/test/raft_test.cpp
Fixed the bug where the log was not being read into storage when the node was restarted.
> KEP-433: Load storage from log on restart

- options/simple_options.cpp
- options/simple_options.hpp
- raft/raft.cpp
- raft/raft.hpp
- swarm/main.cpp
The issue is that a new daemon starting with a large state dir will
replay its entire history, sending an audit notification for each
message that's committed. For now, I'm just disabling audit by default.
In pbft, messages will not be replayed in this way so it won't be such a
concern.
> KEP-616: Out of file handlers

- README.md
- raft/raft.cpp
- raft/raft.hpp
- raft/test/raft_test.cpp
Implemented the web socket command get_peers. Send a get peers command:
{"cmd": "get_peers", "bzn-api": "raft"}
via wscat to the leader and you will get 
{
"message" :
[
{
"host" : "127.0.0.1",
"http_port" : 9082,
"name" : "peer0",
"port" : 49152,
"uuid" : "7b49e6e8-0408-459c-bb97-0036ca695363"
},
{
"host" : "127.0.0.1",
"http_port" : 9083,
"name" : "peer1",
"port" : 49153,
"uuid" : "b5dde374-90f3-46d3-8f20-e9815f7a5ae0"
}
]
}
to a follower, you'll get:
{
"error" : "ERROR_GET_PEERS_MUST_BE_SENT_TO_LEADER",
"message" :
{
"leader" :
{
"host" : "127.0.0.1",
"http_port" : 9082,
"name" : "peer0",
"port" : 49152,
"uuid" : "7b49e6e8-0408-459c-bb97-0036ca695363"
}
}
}
Sending it to a candidate will get you a message telling you that an election is in progress, try later..
> KEP-497 Get Active Peer List for Given Node

- pbft/pbft.cpp
- pbft/pbft.hpp
- pbft/pbft_base.hpp
- pbft/pbft_operation.cpp
- pbft/pbft_operation.hpp
- pbft/test/pbft_audit_test.cpp
- pbft/test/pbft_checkpoint_tests.cpp
- pbft/test/pbft_operation_test.cpp
- pbft/test/pbft_test.cpp
- pbft/test/pbft_test_common.cpp
- pbft/test/pbft_test_common.hpp
- proto/pbft.proto
The new structure is that pbft handlers take references to both the pbft_msg and the original wrapped_bzn_msg that contained it. The reason is that they need to do stuff based on the data contained in the message, but they also potentially need to store the original signed message for later forwarding. If they re-serialized their serialized copy, they could break the signature because serialization in protobuf is not guaranteed to be deterministic.
> KEP-652: refactoring to remove sender field in pbft_msg

- pbft/CMakeLists.txt
- pbft/pbft.cpp
- pbft/pbft.hpp
- pbft/pbft_config_store.cpp
- pbft/pbft_config_store.hpp
- pbft/pbft_configuration.cpp
- pbft/pbft_configuration.hpp
- pbft/test/CMakeLists.txt
- pbft/test/pbft_config_store_test.cpp
- pbft/test/pbft_configuration_test.cpp
Code for storing PBFT peers in an abstract "configuration" that can be versioned and passed as a message. The configuration class stores an individual config. The config_store class stores multiple configurations in order of adding, accesses them by hash, supports setting a configuration "enabled" and selecting a current configuration, as well as purging old ones.
The main PBFT code was updated to store the initial peers list in configuration and access it from there.
> KEP-574 pbft - configurations

- pbft/pbft.cpp
- pbft/pbft.hpp
- pbft/test/CMakeLists.txt
- pbft/test/pbft_catchup_test.cpp
- pbft/test/pbft_join_leave_test.cpp
- pbft/test/pbft_proto_test.cpp
- pbft/test/pbft_proto_test.hpp
- pbft/test/pbft_test_common.cpp
- pbft/test/pbft_test_common.hpp
- proto/database.proto
- proto/pbft.proto
Implementation of node state catchup. When a node sees a stable checkpoint that it doesn't have locally, it assumes it is behind and requests the database state at that point. When it receives the state it populates its database, which allows it to apply any pending operations after the checkpoint and get caught up.
> KEP-613: New node gets caught up from old nodes

- pbft/pbft.cpp
- pbft/pbft.hpp
- pbft/test/CMakeLists.txt
- pbft/test/pbft_proto_test.cpp
- pbft/test/pbft_proto_test.hpp
- pbft/test/pbft_timestamp_test.cpp
…even if the request is duplicated
Not sure if Ed needs to review this but added him out of courtesy.
> KEP-329: Primary should only send out preprepares once for each request

- mocks/mock_session_base.hpp
- node/session.cpp
- node/session.hpp
- node/session_base.hpp
- pbft/database_pbft_service.cpp
- pbft/dummy_pbft_service.cpp
- pbft/pbft.cpp
- pbft/pbft.hpp
- pbft/pbft_operation.cpp
- pbft/pbft_operation.hpp
- pbft/test/database_pbft_service_test.cpp
- pbft/test/pbft_test.cpp
- scripts/crud
fix some lingering bugs that prevented that response from being sent
the session is held as a shared_ptr instead of a weak_ptr because, between pbft's ack and crud's response, no operations are pending on that session and it will otherwise be cleaned up.
> KEP-843, KEP-845: Update crud script to handle new pbft response style,

- crud/crud.cpp
- crud/raft_crud.cpp
- crud/subscription_manager.cpp
- crud/test/crud_test.cpp
- crud/test/raft_crud_test.cpp
- crud/test/subscription_manager_test.cpp
- pbft/test/database_pbft_service_test.cpp
- pbft/test/pbft_test.cpp
- proto/database.proto
- raft/test/raft_test.cpp
- PBFT requires a nonce to uniquely identify transactions
- The nonce can be used instead of transaction_id for the same purposes
> database.proto eliminate transaction_id and replace with nonce

- crud/crud.cpp
- crud/test/crud_test.cpp
- mocks/mock_node_base.hpp
- mocks/mock_session_base.hpp
- node/node.cpp
- node/node.hpp
- node/node_base.hpp
- node/session.cpp
- node/session.hpp
- node/session_base.hpp
- node/test/session_test.cpp
- pbft/pbft.cpp
- pbft/test/pbft_audit_test.cpp
- pbft/test/pbft_catchup_test.cpp
- pbft/test/pbft_checkpoint_tests.cpp
- pbft/test/pbft_join_leave_test.cpp
- pbft/test/pbft_newview_test.cpp
- pbft/test/pbft_proto_test.cpp
- pbft/test/pbft_test.cpp
- pbft/test/pbft_timestamp_test.cpp
- pbft/test/pbft_viewchange_test.cpp
- proto/database.proto
- scripts/crud
- status/status.cpp
- status/test/status_test.cpp
changed point of contact field to string
removed placeholder uuids from crud
moved message signing into session, changed method names to clarify
intent
> KEP-1092: Integration fixes for signature collation

- pbft/CMakeLists.txt
- pbft/database_pbft_service.cpp
- pbft/pbft.cpp
- pbft/pbft.hpp
- pbft/pbft_config_store.cpp
- pbft/pbft_config_store.hpp
- pbft/pbft_configuration.cpp
- pbft/pbft_configuration.hpp
- pbft/pbft_persistent_state.cpp
- pbft/pbft_persistent_state.hpp
- pbft/test/CMakeLists.txt
- pbft/test/pbft_config_store_test.cpp
- pbft/test/pbft_join_leave_test.cpp
- pbft/test/pbft_newview_test.cpp
- pbft/test/pbft_persistent_state_test.cpp
- pbft/test/pbft_test_common.cpp
- pbft/test/pbft_viewchange_test.cpp
- storage/rocksdb_storage.cpp
- swarm/main.cpp
Persistently stored variable framework and usage in PBFT.
I recommend reading the block comment in pbft_persistent_storage.hpp first. The intention was to hide all the complexity in there and make using the variables as easy as possible, but there are a couple of scenarios that are a little tricky.
> KEP-973: pbft variables reside in storage

- crypto/crypto.cpp
Workaround for signature validation problem. Based on my tests ec256k1 is not reliable between openssl and JS elliptic library when using SHA512 hashes, whereas SHA256 hashes don't exhibit the same problem.
> KEP-1111: Changed encryption to use SHA256 hash instead of SHA512

- crypto/crypto.cpp
- pbft/pbft.cpp
- pbft/pbft.hpp
- pbft/test/pbft_join_leave_test.cpp
- messages didn't have sender set if cryto disabled
- missing lock
- corruption of checkpoint stack variable leading to bad water mark
settings in pbft
For the last one - checkpoint just emplace'd passed by reference to function (stabilize_checkpoint) that destroys it (clear_local_checkpoints_until) then uses it to set low_water_mark/high_water_mark, leading to arbitrary watermark values causing subsequent messages to be rejected.
> Fixes for a couple of bugs:

- pbft/pbft.cpp
- pbft/pbft.hpp
- pbft/test/pbft_viewchange_test.cpp
In the case where a new node joins and the ensuing viewchange causes it to be primary, the next_sequence_number_issued was never updated correctly because it was originally set when the newview was generated. In this case, the node sending the newview didn't end up being primary, so the new node (new primary) had a default value for next_sequence_number_issued.
The modified code now calculates the next sequence number from the incoming newview message, instead of when the newview message is built.
> KEP-1202: update next_sequence number from newview

- crypto/crypto.cpp
- pbft/database_pbft_service.cpp
- pbft/pbft.cpp
- pbft/pbft.hpp
- pbft/pbft_persistent_state.hpp
- pbft/test/pbft_join_leave_test.cpp
- pbft/test/pbft_persistent_state_test.cpp
- pbft/test/pbft_viewchange_test.cpp
- storage/test/storage_test.cpp
Bugfixes from devel to be merged into 0.5 release:
KEP-1231: forward declarations for template specializations (#259)
KEP-1169: Notify failure detector when forwarded join request is executed (#257)
KEP-1236: fix for race condition processing operations (#260)
Fixes for a couple of bugs: (#253)
KEP-1202: update next_sequence number from newview (#258)
> Merge bugfixes to 0.5

- include/boost_asio_beast.hpp
- mocks/mock_boost_asio_beast.hpp
- node/session.cpp
- node/session.hpp
- node/test/node_test_common.hpp
- node/test/session_test.cpp
- utils/bytes_to_debug_string.cpp
Strand used for synchronization throughout
Do not start idle timeout until handshake sucessful
Cancel idle timeout early when socket closes, so session can be cleaned
up
> KEP-1239: Several safety fixes in session

- proto/pbft.proto
One-liner. Fixes issue with being unable to parse payload of state message.
> KEP-1247 - changed proto to use bytes for state instead of string

- pbft/database_pbft_service.cpp
- pbft/pbft.cpp
Added a lock to pbft::handle_database_request
Cleaned up a couple of log messages to work better for large db values
> KEP-1294: missing lock causing instability of swarm (devel)

- pbft/database_pbft_service.cpp
- pbft/pbft.cpp
- utils/test/utils_test.cpp
Added a lock to pbft::handle_database_request
Cleaned up a couple of log messages to work better for large db values
> KEP-1294: missing lock causing instability of swarm

- mocks/mock_pbft_base.hpp
- node/node.cpp
- node/session.cpp
- node/session.hpp
- node/test/session_test.cpp
- pbft/pbft.hpp
- pbft/test/pbft_proto_test.cpp
- pbft/test/pbft_test.cpp
- proto/bluzelle.proto
Added swarm id to the bzn_envelope protobuf structure and propagated the changes through the code. The swarm id parameter is set in pbft::wrap_message method.
> kep-1144 Add Swarm ID to all swarm<>swarm and swarm<>client messages

- pbft/pbft.cpp
- pbft/pbft.hpp
Fix for issue on testnet where bad client timestamp was causing viewchanges to occur.
> KEP-1606 - don't forward messages with invalid timestamps

- monitor/monitor.cpp
- pbft/operations/pbft_persistent_operation.cpp
- pbft/pbft.cpp
Set some less than useful and verbose messages to "trace" level. Right now we don't have a way to enable trace messages but that could be added later.
> KEP-1605 - reduce impact of log messages
